//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Collections.Generic;
    
    public partial class AET_IMAGE_EXAM
    {
        public AET_IMAGE_EXAM()
        {
            this.AET_IMAGE_EXAM_RESULT = new HashSet<AET_IMAGE_EXAM_RESULT>();
        }
    
        public string PanelId { get; set; }
        public int Indexid { get; set; }
        public string Judge { get; set; }
        public string DefectCode { get; set; }
        public string DefectName { get; set; }
        public string Info { get; set; }
        public int DelFlag { get; set; }
    
        public virtual ICollection<AET_IMAGE_EXAM_RESULT> AET_IMAGE_EXAM_RESULT { get; set; }
    }
}
