//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DICS_DBEntities : DbContext
    {
        public DICS_DBEntities()
            : base("name=DICS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AET_IMAGE_EXAM> AET_IMAGE_EXAM { get; set; }
        public DbSet<AET_IMAGE_EXAM_RESULT> AET_IMAGE_EXAM_RESULT { get; set; }
        public DbSet<FinishedLot> FinishedLot { get; set; }
        public DbSet<InspectResult> InspectResult { get; set; }
        public DbSet<OnInspectLot> OnInspectLot { get; set; }
        public DbSet<OninspectProduct> OninspectProduct { get; set; }
        public DbSet<Panel> Panel { get; set; }
        public DbSet<ProductInfo> ProductInfo { get; set; }
        public DbSet<TrayLot> TrayLot { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<WaitLot> WaitLot { get; set; }
    }
}
