//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DICS_DBEntities : DbContext
    {
        public DICS_DBEntities()
            : base("name=DICS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FinishedLot> FinishedLot { get; set; }
        public DbSet<InspectResult> InspectResult { get; set; }
        public DbSet<OnInspectLot> OnInspectLot { get; set; }
        public DbSet<OninspectProduct> OninspectProduct { get; set; }
        public DbSet<Panel> Panel { get; set; }
        public DbSet<ProductInfo> ProductInfo { get; set; }
        public DbSet<TrayLot> TrayLot { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<WaitLot> WaitLot { get; set; }
    }
}
