//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinishedLot
    {
        public int LotId { get; set; }
        public string EndTime { get; set; }
        public int Operater { get; set; }
    
        public virtual TrayLot TrayLot { get; set; }
        public virtual User User { get; set; }
    }
}
