//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectResult
    {
        public int Indexid { get; set; }
        public string LOTGRADE { get; set; }
        public string LOTDETAILGRADE { get; set; }
        public int operaterId { get; set; }
        public string EndTime { get; set; }
        public string DefectCode { get; set; }
        public string DefectName { get; set; }
    
        public virtual Panel Panel { get; set; }
        public virtual User User { get; set; }
    }
}
