//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectResult
    {
        public int Indexid { get; set; }
        public string LOTGRADE { get; set; }
        public string LOTDETAILGRADE { get; set; }
        public int operaterId { get; set; }
        public string EndTime { get; set; }
        public string DefectCode { get; set; }
        public string DefectName { get; set; }
    
        public virtual Panel Panel { get; set; }
        public virtual User User { get; set; }
    }
}
