//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panel
    {
        public int IndexId { get; set; }
        public string PanelId { get; set; }
        public int LotId { get; set; }
        public int PIAOI1PANELJUDGE { get; set; }
        public int PIAOI2PANELJUDGE { get; set; }
        public int TFEAOIPANELJUDGE { get; set; }
        public int ACTAOIPANELJUDGE { get; set; }
        public string LastGrade { get; set; }
        public string LastDetailGrade { get; set; }
    
        public virtual InspectResult InspectResult { get; set; }
        public virtual TrayLot TrayLot { get; set; }
    }
}
