//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public ProductInfo()
        {
            this.TrayLot = new HashSet<TrayLot>();
        }
    
        public int IndexId { get; set; }
        public string Name { get; set; }
        public string ProductType { get; set; }
        public string FGcode { get; set; }
    
        public virtual OninspectProduct OninspectProduct { get; set; }
        public virtual ICollection<TrayLot> TrayLot { get; set; }
    }
}
