//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrayLot
    {
        public TrayLot()
        {
            this.Panel = new HashSet<Panel>();
        }
    
        public int Lotid { get; set; }
        public string TrayGroupName { get; set; }
        public string MachineName { get; set; }
        public string AddTime { get; set; }
        public int ProductInfo { get; set; }
    
        public virtual FinishedLot FinishedLot { get; set; }
        public virtual OnInspectLot OnInspectLot { get; set; }
        public virtual ICollection<Panel> Panel { get; set; }
        public virtual ProductInfo ProductInfo1 { get; set; }
        public virtual WaitLot WaitLot { get; set; }
    }
}
