//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Container
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.FinishedLot = new HashSet<FinishedLot>();
            this.InspectResult = new HashSet<InspectResult>();
            this.OnInspectLot = new HashSet<OnInspectLot>();
        }
    
        public int IndexId { get; set; }
        public string UserName { get; set; }
        public string UserId { get; set; }
        public string PassWord { get; set; }
        public int Grade { get; set; }
    
        public virtual ICollection<FinishedLot> FinishedLot { get; set; }
        public virtual ICollection<InspectResult> InspectResult { get; set; }
        public virtual ICollection<OnInspectLot> OnInspectLot { get; set; }
    }
}
